### ISSUE TITLE
Dependencies on hspec < 2.1

### ISSUE THREAD

**Issue by jsantos17** [dbp/hspec-snap#7]
I just built it against 2.1.4 and all the tests pass. Am I missing something here? This restriction is preventing hspec-snap from working with Stackage.

**Comment by dbp** [comment]
This package follows PVP (https://wiki.haskell.org/Package_versioning_policy), which means that there are always upper bounds, by default one minor version higher than the known / released version. Since according to the PVP, APIs are permitted to change with minor version bumps, this is a conservative policy that means that when dependencies can be satisfied, they should build. Of course, just because there can be breaking changes doesn't mean they necessarily affect all uses, which is what has happened here - the dependency should be < 2.2, not < 2.1.

Feel free to file a pull request updating the bound to < 2.2. If you don't want to, I'll try to update it myself soon, and regardless I'll release it as soon as that happens.

**Comment by dbp** [comment]
This has been released to hackage as 0.3.2.3 - thanks!
